server.port=80
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

transbank.webpayplusCommerceCode = ${webpayplusCommerceCode}
transbank.webpayplusApiKey = ${webpayplusApiKey}

transbank.webpayplusMallCommerceCode = ${webpayplusMallCommerceCode}
transbank.webpayplusMallApiKey = ${webpayplusMallApiKey}

transbank.oneclickMallCommerceCode = ${oneclickMallCommerceCode}
transbank.oneclickMallApiKey = ${oneclickMallApiKey}

transbank.patpassComercioCommerceCode = ${patpassComercioCommerceCode}
transbank.patpassComercioApiKey = ${patpassComercioApiKey}

transbank.fullTransactionCommerceCode = ${fullTransactionCommerceCode}
transbank.fullTransactionApiKey = ${fullTransactionApiKey}